- name: Install and configure Apache
  hosts: "{{ host }}"
  become: yes
  vars:
    http_port: 80
    https_port: 443
    domain: "{{ host }}"
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: Install libapache php mod
      apt: name=libapache2-mod-php7.1 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ http_port }}
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ http_port }}
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: create virtual host file
      template: src=../templates/virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2

    - name: Deactivates the default virtualhost
      command: a2dissite 000-default
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted