- name: Prepare Composer
  hosts: "{{ host }}"
  vars:
    path: /usr/bin/composer

  tasks:
    - name: composer | install
      get_url: url=http://getcomposer.org/composer.phar dest={{ path }} owner=root group=root mode=0755
      tags: composer
      become: yes
      become_method: sudo

    - name: composer | install update cron
      cron: name="update composer" user="root" special_time="weekly" job="{{ path }} self-update --quiet"
      tags: composer
      become: yes
      become_method: sudo

    - name: Composer Token
      command: composer config --global github-oauth.github.com {{ git_token }}